
---
apiVersion: v1alpha1
kind: Pipeline
metadata:
  name: demo-webapp
  namespace: acaleph
spec:
  selector:
    matchLabels:
      app: acaleph
  template:
    metadata:
      name: acaleph
      labels:
        app: demo-webapp
    stages:
      - name: Build Image
        type: docker_build
        params:
          dockerfile_path: .
          dockerfile_name: Dockerfile

